version: 2.1
orbs:
  node: circleci/node@4.1.0

executors:
  node:
    docker:
      - image: cimg/node:16.6

jobs:
  test:
    working_directory: ~/navigo
    executor: node
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Add NPMRC
          command: |
            echo "@zepdev:registry=https://npm.pkg.github.com/" > ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=\"$GITHUB_TOKEN\"" >> ~/.npmrc
            npm set @zepdev:registry https://npm.pkg.github.com
      - node/install-packages
      - attach_workspace:
          at: ~/navigo
      - run:
          name: "run unit tests"
          command: "npm run test"

  build_and_release:
    working_directory: ~/navigo
    executor: node
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Add NPMRC
          command: |
            echo "@zepdev:registry=https://npm.pkg.github.com/" > ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=\"$GITHUB_TOKEN\"" >> ~/.npmrc
            npm set @zepdev:registry https://npm.pkg.github.com
      - node/install-packages
      - attach_workspace:
          at: ~/navigo
      - run:
          name: Build
          command: npm run build-es
      - run:
          name: release
          command: npm publish

workflows:
  version: 2
  test_build_release:
    jobs:
#      - test:
#          context: Avengers

      - build_and_release:
          context: Avengers
          filters:
            branches:
              only:
                - master
#          requires:
#            - test
